services:
  backend:
    build: 
      context: ./server/
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 3001:3001
  app:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - 5173:3000
    depends_on:
      - backend