const SUCCESS_CODE_STATUS = 200;
const CREATED_CODE_STATUS = 201;
const BAD_REQUEST_CODE_STATUS = 400;
const NOT_FOUND_CODE_STATUS = 404;
const INTERNAL_SERVER_ERROR_CODE_STATUS = 500;

export default {
  SUCCESS_CODE_STATUS,
  CREATED_CODE_STATUS,
  BAD_REQUEST_CODE_STATUS,
  NOT_FOUND_CODE_STATUS,
  INTERNAL_SERVER_ERROR_CODE_STATUS
};
